package com.fitnessgame;

/**
 * Automatically generated by Gradle when the build is run.
 * Compilation will fail until you generate a valid BuildConfig.java
 */
public final class BuildConfig {
    public static final boolean DEBUG = true;
    public static final String APPLICATION_ID = "com.fitnessgame";
    public static final String BUILD_TYPE = "debug";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0.0";
    public static final boolean IS_NEW_ARCHITECTURE_ENABLED = false;
    public static final boolean IS_HERMES_ENABLED = false;
}
